# Generated by Django 3.2 on 2022-11-24 04:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_deed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('deed_no', models.IntegerField()),
                ('land_no', models.IntegerField()),
                ('book_no', models.IntegerField()),
                ('page_no', models.IntegerField()),
                ('survey_page_number', models.IntegerField()),
                ('tam_code', models.CharField(max_length=100)),
                ('amp_code', models.CharField(max_length=100)),
                ('prov_code', models.CharField(max_length=100)),
                ('rai_number', models.IntegerField()),
                ('ngarn_number', models.IntegerField()),
                ('sqw_number', models.FloatField()),
                ('date_add', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
